import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Check } from 'lucide-react';
import { createModelResponse, getModelResponse, getModelResponses, updateModelResponse } from '@/api/model-responses';
import { PageHead } from '@/components/layout/PageHead';
import { MarkdownEditorPanel } from '@/components/markdown/MarkdownEditorPanel';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { useToast } from '@/hooks/use-toast';
import type { ModelResponsePayload } from '@/types/domain';

const emptyForm: ModelResponsePayload = { title: '', summary: '', content: '', category: '', tags: [], sourceProduct: '', modelName: '', originalPrompt: '' };
/** 解析粘贴的标签，保持与学习笔记的标签去重语义一致。 */
function parseTags(value: string): string[] { return Array.from(new Set(value.split(/[,，]/).map((tag) => tag.trim()).filter(Boolean))); }

export function ModelResponseEditor() {
  const { id } = useParams<{ id: string }>(); const navigate = useNavigate(); const { toast } = useToast(); const isEdit = Boolean(id);
  const [saving, setSaving] = useState(false); const [categories, setCategories] = useState<string[]>([]); const [tagsText, setTagsText] = useState(''); const [form, setForm] = useState<ModelResponsePayload>(emptyForm);
  useEffect(() => { const bootstrap = async () => { const list = await getModelResponses(); setCategories(Array.from(new Set(list.map((item) => item.category).filter(Boolean)))); if (isEdit && id) { const record = await getModelResponse(id); setForm({ title: record.title, summary: record.summary, content: record.content, category: record.category, tags: record.tags, sourceProduct: record.sourceProduct, modelName: record.modelName, originalPrompt: record.originalPrompt }); setTagsText(record.tags.join(', ')); } }; void bootstrap(); }, [id, isEdit]);
  const handleSubmit = async () => { if (!form.title.trim()) { toast({ title: '请输入标题', variant: 'destructive' }); return; } if (!form.content.trim()) { toast({ title: '请粘贴模型回答正文', variant: 'destructive' }); return; } const tags = parseTags(tagsText); if (!tags.length) { toast({ title: '请至少添加一个标签', variant: 'destructive' }); return; } setSaving(true); try { const payload: ModelResponsePayload = { ...form, title: form.title.trim(), summary: form.summary.trim(), category: form.category.trim(), tags, sourceProduct: form.sourceProduct.trim(), modelName: form.modelName.trim(), originalPrompt: form.originalPrompt.trim() }; const record = isEdit && id ? await updateModelResponse(id, payload) : await createModelResponse(payload); toast({ title: '模型回答已保存', variant: 'success' }); navigate(`/model-responses/${record.id}`); } finally { setSaving(false); } };
  return <section><PageHead title={isEdit ? '编辑模型回答' : '收录回答'} subtitle="粘贴模型回答正文，并可选记录来源产品、模型与原始 Prompt。" back={isEdit && id ? `/model-responses/${id}` : '/model-responses'} actions={<Button disabled={saving} onClick={() => void handleSubmit()}><Check className="h-4 w-4" />{saving ? '保存中...' : '保存'}</Button>} /><div className="editor-layout"><div className="form-surface"><div className="form-grid"><label className="form-field"><span className="form-label">标题 <span className="text-destructive">*</span></span><Input value={form.title} maxLength={200} placeholder="概括这份回答的主题" onChange={(event) => setForm((current) => ({ ...current, title: event.target.value }))} /></label><label className="form-field"><span className="form-label">摘要</span><Textarea value={form.summary} maxLength={500} rows={3} placeholder="用于列表快速识别的简短摘要" onChange={(event) => setForm((current) => ({ ...current, summary: event.target.value }))} /></label><label className="form-field"><span className="form-label">来源产品</span><Input value={form.sourceProduct} maxLength={120} placeholder="例如 ChatGPT、Claude、Gemini" onChange={(event) => setForm((current) => ({ ...current, sourceProduct: event.target.value }))} /></label><label className="form-field"><span className="form-label">模型名称</span><Input value={form.modelName} maxLength={120} placeholder="例如 GPT-5" onChange={(event) => setForm((current) => ({ ...current, modelName: event.target.value }))} /></label><label className="form-field"><span className="form-label">分类</span><Input value={form.category} maxLength={80} list="model-response-category-options" placeholder="例如 前端、产品设计" onChange={(event) => setForm((current) => ({ ...current, category: event.target.value }))} /><datalist id="model-response-category-options">{categories.map((category) => <option key={category} value={category} />)}</datalist></label><label className="form-field"><span className="form-label">标签 <span className="text-destructive">*</span></span><Input value={tagsText} placeholder="多个标签用逗号分隔" onChange={(event) => setTagsText(event.target.value)} /><span className="text-xs text-muted-foreground">至少填写一个，最多 20 个，自动去重。</span></label><label className="form-field form-field-wide"><span className="form-label">原始 Prompt</span><Textarea value={form.originalPrompt} maxLength={50000} rows={4} placeholder="可选，记录生成该回答时的原始提问" onChange={(event) => setForm((current) => ({ ...current, originalPrompt: event.target.value }))} /></label></div></div><MarkdownEditorPanel title="回答正文" value={form.content} onChange={(content) => setForm((current) => ({ ...current, content }))} /></div></section>;
}
